---
# tasks file for crane_hack

# 
- name: get user home directory
  shell: >
    getent passwd `whoami` | awk -F: '{ print $6 }'
  changed_when: false
  register: user_home

- name: Make a directory for source checkouts
  file:
    path: "{{ user_home.stdout }}/src"
    state: directory

- name: Install/Upgrade misc packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - git  
    - jq
  become: yes

# Add to path

- git:
    repo: 'https://github.com/konveyor/hackfest.git'
    dest: "{{ user_home.stdout }}/hackfest"

- git:
    repo: 'https://github.com/konveyor/crane.git'
    dest: "{{ user_home.stdout }}/src/crane"

- git:
    repo: 'https://github.com/konveyor/crane-lib.git'
    dest: "{{ user_home.stdout }}/src/crane-lib"

- git:
    repo: 'https://github.com/konveyor/crane-documentation.git'
    dest: "{{ user_home.stdout }}/src/crane-documentation"

    