---
# tasks file for crane_hack

# 
- name: get user home directory
  shell: >
    getent passwd `whoami` | awk -F: '{ print $6 }'
  changed_when: false
  register: user_home

- name: Make a directory for source checkouts
  file:
    path: "{{ user_home.stdout }}/src"
    state: directory

- name: Install/Upgrade misc packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - git  
    - jq
  become: yes

- git:
    repo: 'https://github.com/konveyor/hackfest.git'
    dest: "{{ user_home.stdout }}/hackfest"

- git:
    repo: 'https://github.com/konveyor/crane.git'
    dest: "{{ user_home.stdout }}/src/crane"

- git:
    repo: 'https://github.com/konveyor/crane-lib.git'
    dest: "{{ user_home.stdout }}/src/crane-lib"

- git:
    repo: 'https://github.com/konveyor/crane-documentation.git'
    dest: "{{ user_home.stdout }}/src/crane-documentation"

- file:
    src: "{{ item.path }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { path: "{{ user_home.stdout }}/src/crane/hack/minikube-clusters-start.sh", dest: "{{ user_home.stdout }}/minikube-clusters-start.sh" }
    - { path: "{{ user_home.stdout }}/src/crane/hack/minikube-clusters-delete.sh", dest: "{{ user_home.stdout }}/minikube-clusters-delete.sh" }

- name: Download crane binary
  get_url:
    url: https://github.com/konveyor/crane/releases/download/v0.0.3/amd64-linux-crane-v0.0.3
    dest: "{{ user_home.stdout }}/bin/crane"
    mode: '0777'

- name: Run minikube-clusters-start.sh
  command: "./minikube-clusters-start.sh"
  args:
    chdir: "{{ user_home.stdout }}"
    creates: "{{ user_home.stdout }}/.minikube/profiles/src/config.json"

